name: Build

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy credential file
        run: cp ./.env.example ./.env

      - name: Build images
        run: make build

      - name: Run Containers
        run: make up
